"""
Dot plot to visualize relationship between two sequences
"""

import os
import sys
import tempfile
from optparse import OptionParser

from jcvi.apps.base import ActionDispatcher, sh


def main():

    actions = (
        ('rdotplot', 'visualize .rdotplot file (often generated by LASTZ)'),
            )

    p = ActionDispatcher(actions)
    p.dispatch(globals())


def rdotplot(args):
    """
    %prog test.rdotplot

    visualize .rdotplot file (often generated by LASTZ)
    """
    p = OptionParser(rdotplot.__doc__)
    opts, args = p.parse_args(args)

    if len(args)!=1:
        sys.exit(p.print_help())

    rdotplotfile = args[0]
    assert rdotplotfile.endswith(".rdotplot")
    pngfile = rdotplotfile.replace(".rdotplot", ".png")

    # write to a temporary R script
    fd, path = tempfile.mkstemp()
    fw = os.fdopen(fd, "w")

    fw.write("dots = read.table('%s', header=T)\n" % rdotplotfile)
    fw.write("png('%s')\n" % pngfile)
    fw.write("plot(dots, type='l')\n")
    fw.write("dev.off()\n")
    fw.close()

    sh("Rscript %s" % path)
    os.remove(path)


if __name__ == '__main__':
    main()
