"""
Dot plot to visualize relationship between two sequences
"""

import os
import sys
from optparse import OptionParser

from jcvi.apps.base import ActionDispatcher
from jcvi.apps.R import RTemplate


dotplot_template = """
dots <- read.table('$rdotplotfile', header=T)
png('$pngfile')
plot(dots, type='l')
dev.off()
"""

def main():

    actions = (
        ('rdotplot', 'visualize .rdotplot file (often generated by LASTZ)'),
            )

    p = ActionDispatcher(actions)
    p.dispatch(globals())


def rdotplot(args):
    """
    %prog test.rdotplot

    visualize .rdotplot file (often generated by LASTZ)
    """
    p = OptionParser(rdotplot.__doc__)
    opts, args = p.parse_args(args)

    if len(args)!=1:
        sys.exit(p.print_help())

    rdotplotfile = args[0]
    assert rdotplotfile.endswith(".rdotplot")
    pngfile = rdotplotfile.replace(".rdotplot", ".png")

    rtemplate = RTemplate(dotplot_template, locals())
    rtemplate.run()


if __name__ == '__main__':
    main()
