#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
%prog test.rdotplot

Dot plot to visualize relationship between two sequences, by plotting
.rdotplot file (often generated by LASTZ)
"""

import os
import sys
from optparse import OptionParser

from jcvi.apps.base import ActionDispatcher
from jcvi.apps.R import RTemplate


dotplot_template = """
dots <- read.table('$rdotplotfile', header=T)
png('$pngfile')
plot(dots, type='l')
dev.off()
"""


def main():

    p = OptionParser(__doc__)
    opts, args = p.parse_args()

    if len(args) != 1:
        sys.exit(p.print_help())

    rdotplotfile = args[0]
    assert rdotplotfile.endswith(".rdotplot")
    pngfile = rdotplotfile.replace(".rdotplot", ".png")

    rtemplate = RTemplate(dotplot_template, locals())
    rtemplate.run()


if __name__ == '__main__':
    main()
