name: jcvi
channels:
  - conda-forge
  - bioconda
dependencies:
  - python 3.12
  - bedtools
  - imagemagick
  - libmagic # System-level magic library
  - wand # Python bindings for ImageMagick
  - last=1256 # MCscan requirement
  - pip
  - pip:
      - pytest
      - hatch
